// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD59qC2edvrN_p9BrAwaPZllrjCMbUxRoc',
    appId: '1:38334664992:web:f6858a14c04ae1c4428745',
    messagingSenderId: '38334664992',
    projectId: 'foodapp-53ebd',
    authDomain: 'foodapp-53ebd.firebaseapp.com',
    storageBucket: 'foodapp-53ebd.appspot.com',
    measurementId: 'G-NTSE997FQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaPA6YleVc1B8lTVJYOCcKZ4vfLcoEadc',
    appId: '1:38334664992:android:90c5bd4ba56bcc12428745',
    messagingSenderId: '38334664992',
    projectId: 'foodapp-53ebd',
    storageBucket: 'foodapp-53ebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8-pZiX03HrgXDpamScgikLs8MISmLsco',
    appId: '1:38334664992:ios:d5ef67228ef6aa43428745',
    messagingSenderId: '38334664992',
    projectId: 'foodapp-53ebd',
    storageBucket: 'foodapp-53ebd.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8-pZiX03HrgXDpamScgikLs8MISmLsco',
    appId: '1:38334664992:ios:d5ef67228ef6aa43428745',
    messagingSenderId: '38334664992',
    projectId: 'foodapp-53ebd',
    storageBucket: 'foodapp-53ebd.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD59qC2edvrN_p9BrAwaPZllrjCMbUxRoc',
    appId: '1:38334664992:web:90074a5208c893f7428745',
    messagingSenderId: '38334664992',
    projectId: 'foodapp-53ebd',
    authDomain: 'foodapp-53ebd.firebaseapp.com',
    storageBucket: 'foodapp-53ebd.appspot.com',
    measurementId: 'G-643LBMJN3E',
  );
}
